<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lixionggang-PC" name="192.168.56.102:5555" tests="3" failures="2" timestamp="18 Jun 2016 08:59:11 GMT" time="93.361" errors="0">
  <testcase name="login" time="34.948" classname="cn.crazy.appium.network.study.ZhiHu">
    <skipped/>
  </testcase> <!-- login -->
  <testcase name="login" time="34.274" classname="cn.crazy.appium.network.study.ZhiHu">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at cn.crazy.appium.testng.Assertion.fail(Assertion.java:63)
	at cn.crazy.appium.testng.Assertion.assertEquals(Assertion.java:19)
	at cn.crazy.appium.network.study.ZhiHu.login(ZhiHu.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="modifyPersionInfo" time="10.235" classname="cn.crazy.appium.network.study.ZhiHu">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at cn.crazy.appium.network.study.ZhiHu.modifyPersionInfo(ZhiHu.java:62)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- modifyPersionInfo -->
</testsuite> <!-- 192.168.56.102:5555 -->
